# Generated by Django 4.1.3 on 2022-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=150)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True)),
            ],
        ),
    ]
