# Generated by Django 4.1.3 on 2022-12-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=150, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True, max_length=150)),
            ],
        ),
    ]
