# Generated by Django 4.1.3 on 2022-11-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_client_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="discount",
        ),
    ]
