# Generated by Django 4.1.3 on 2022-11-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_remove_client_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="name",
            new_name="firstname",
        ),
    ]
