# Generated by Django 4.1.3 on 2022-12-14 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
