# Generated by Django 4.1.3 on 2022-12-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#eeeeee", max_length=7)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                        ],
                        default="NEW",
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
