# Generated by Django 4.1.3 on 2022-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="state",
            field=models.CharField(
                choices=[("NEW", "New"), ("PENDING", "Pending"), ("DONE", "Done")],
                default="NEW",
                max_length=8,
            ),
        ),
    ]
